// `npm run mutate`: a check is trusted only after it has been seen red (cards-lite M5). Each mutation
// breaks one rule in a source file, runs the gate that guards it, and must make that gate fail.
// Safety: before a file is mutated its original bytes are written to temp/mutate/ (gitignored); they
// are restored after every mutation, on exit and on Ctrl-C/hang-up — never through git. A run killed
// hard leaves the backup, and the next run restores it before doing anything else. An anchor that no
// longer matches exactly once is a failure too: the list has drifted from the source.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const TEST = [process.execPath, ['--test', 'test/*.test.mjs']];
const TYPES = [process.execPath, ['node_modules/typescript/bin/tsc', '-p', 'tsconfig.json']];
const BUNDLE = [process.execPath, ['scripts/bundle-gate.mjs']];
// the series tests with a 128 MB heap: a mutation that loops while allocating dies fast instead of eating the machine
const CAPPED = [process.execPath, ['--max-old-space-size=128', '--test', 'test/series.test.mjs']];
const T = TEST, C = 'charts.js', F = 'charts-funnel.js', W = 'charts-waterfall.js', S = 'charts-series.js', K = 'charts-spark.js', RK = 'charts-rank.js', SH = 'charts-share.js', HM = 'charts-heatmap.js', MT = 'charts-meter.js', SK = 'charts-sankey.js';

const MUTATIONS = [
	[C, T, 'esc leaves the apostrophe', ".replace(/'/g, '&#39;')", ''],
	[C, T, 'no title, no aria-hidden', "label ? null : 'true'", 'null'],
	[C, T, 'title without role', "label ? 'img' : null", 'null'],
	[C, T, 'desc not referenced', "label += ' ' + id + '-d';", ''],
	[C, T, 'Infinity accepted', '!isFinite(v)', 'v !== v'],
	[C, T, 'ids ignore the input', "id = p + '-' + hash(key)", "id = p + '-' + hash('')"],
	[C, T, 'no default class prefix', "opts.classPrefix || 'chart'", 'opts.classPrefix'],
	[C, T, 'class prefix unchecked', "if (p !== undefined && (typeof p !== 'string' || !/^[A-Za-z_][\\w-]*$/.test(p))) fail('classPrefix must be a token like \"chart\"');", ''],
	[C, T, 'class prefix may hold a space', '/^[A-Za-z_][\\w-]*$/', '/^[A-Za-z_][\\w -]*$/'],
	[C, T, 'class prefix may be a non-string', "typeof p !== 'string' || ", ''],
	[C, T, 'brand unchecked', "if (o.brand !== undefined && (typeof o.brand !== 'string' || !/^#[0-9a-fA-F]{6}$/.test(o.brand))) fail('brand must be a #rrggbb hex');", ''],
	[C, T, 'brand may be a non-string', "typeof o.brand !== 'string' || ", ''],
	[C, T, 'ids from one 32-bit pass', "return fnv(s, 0x811c9dc5) + fnv(s, 0x5bd1e995);", 'return fnv(s, 0x811c9dc5);'],
	[C, T, 'id halves of any width', "return ('000000' + h.toString(36)).slice(-7);", 'return h.toString(36);'],
	[C, T, 'n prints Infinity', 'if (!isFinite(r)) r = v;', ''],
	[F, T, 'part as a string accepted', "if (s.part != null && typeof s.part !== 'boolean' || s.gap != null && typeof s.gap !== 'boolean') fail(at + ': `part` and `gap` are booleans');", ''],
	[F, T, 'an unknown group ignored', "if (s.group != null && s.group !== 'losses') fail(at + ': the only `group` is \"losses\"');", ''],
	[S, T, 'stacked as a string accepted', "if (o.stacked != null && typeof o.stacked !== 'boolean') fail('`stacked` is a boolean');", ''],
	[SK, T, 'an infinite sankey scale drawn', "if (!(k > 0 && isFinite(k))) fail('flows too small or too large to draw');", ''],
	[SH, T, 'share key lines untitled', "key += _.el('g', [], _.el('title', [], _.esc(s.label + ': ' + s.display)) +", "key += _.el('g', [], '' +"],
	[SK, T, 'sankey key lines untitled', "key += _.el('g', [], title(n.label + ': ' + n.display) + ll.svg);", "key += _.el('g', [], ll.svg);"],
	[C, T, 'theme unchecked', "if (o.theme !== undefined && o.theme !== 'light' && o.theme !== 'dark') fail('theme must be \"light\" or \"dark\"');", ''],
	[F, T, 'unknown form accepted', "if (opts.form != null && opts.form !== 'bars' && opts.form !== 'steps' && opts.form !== 'shape') fail('unknown form');", ''],
	[C, T, 'options may be a string', "if (!o || typeof o !== 'object') fail('options must be an object');", "if (!o) fail('options must be an object');"],
	[C, T, 'title may be a number', "if (o.title !== undefined) str(o.title, 'title');", ''],
	[C, T, 'any caller string accepted', "if (typeof v !== 'string') fail(what + ' must be a string');", ''],
	[F, T, 'module without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-funnel.js');", 'if (!core) return;'],
	[F, T, 'module exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.funnel;'],
	[F, T, 'steps may be any object', "if (!Array.isArray(steps)) fail('`steps` must be an array');", ''],
	[F, T, 'a null step reaches the engine', 'var s = steps[i] || {}', 'var s = steps[i]'],
	[F, T, 'legend shape unchecked', "if (legend != null && !(Array.isArray(legend) && legend.length === 2 && typeof legend[0] === 'string' && typeof legend[1] === 'string')) fail('`legend` must be two strings');", ''],
	[F, T, 'legend may be a string', 'Array.isArray(legend) && legend.length === 2', 'legend.length === 2'],
	[F, T, 'range overflow drawn as nothing', "if (!isFinite(hi - lo)) fail('values too far apart to share a scale');", ''],
	[F, T, 'an unused legend in the ids', 'earned ? opts.legend : null,', 'opts.legend || null,'],
	[C, T, 'truncation splits a surrogate pair', 'if (c >= 0xD800 && c <= 0xDBFF) cut--;', ''],
	[F, T, 'base bar solid beside an earned chart', 'loss ? 0.35 : earned ? pal.opacity : 1, cls', 'loss ? 0.35 : s.earned ? pal.opacity : 1, cls'],
	[F, T, 'ghost crosses a gap', 'if (s.gap) prev = null;', ''],
	[F, T, 'ghost of a value that is not positive', 'prev && prev.value > 0 && !s.part', 'prev && !s.part'],
	[F, T, 'earned without legend', "if (!legend) fail('`earned` needs `legend`');", ''],
	[F, T, 'earned unchecked', "row.push(bar(s.earned, at + ' earned'));", ''],
	[F, T, 'rate type unchecked', "if (s.rate !== undefined && s.rate !== null) _.str(s.rate, at + ' rate');", ''],
	[F, T, 'main step after losses', "} else if (losses) fail(at + ' is a main step after the losses');", '} else if (losses) main += 0;'],
	[F, T, 'losses-only funnel accepted', "if (!main) fail('no main step');", ''],
	[F, T, 'part first', 'if (i === 0 || losses)', 'if (losses)'],
	[F, T, 'part inside losses', 'if (i === 0 || losses)', 'if (i === 0)'],
	[F, T, 'gap on a part', "if (s.gap) fail(at + ': `gap` on a `part`');", ''],
	[F, T, 'shape with earned', "if (shape) fail('`shape` cannot draw `earned`');", ''],
	[F, T, 'shape with losses', "if (shape) fail('`shape` cannot draw losses');", ''],
	[F, T, 'shape with a part', "if (shape) fail('`shape` cannot draw `part`');", ''],
	[F, T, 'shape with a negative', "if (shape && s.value < 0) fail('`shape` cannot draw a negative value');", ''],
	[F, T, 'ids ignore the steps', '\t\treturn key;', '\t\treturn [];'],
	[F, T, 'ids ignore the form', "key.push([opts.form || 'bars', ", 'key.push([',],
	// drawing (M3): layout numbers (ADR 010), scale and signs (ADR 007), percent layout (ADR 009)
	[C, T, 'label line height', 'var LINE = 18,', 'var LINE = 17,'],
	[F, T, 'bar height', 'BAR = 12,', 'BAR = 14,'],
	[F, T, 'part height', 'PART = 8,', 'PART = 12,'],
	[F, T, 'shape height', 'SHAPE = 20,', 'SHAPE = 12,'],
	[F, T, 'row padding', 'PAD = 10,', 'PAD = 8,'],
	[F, T, 'block gap', 'BLOCK = 16,', 'BLOCK = 12,'],
	[F, T, 'steps rate line not taller', 'RATE + 4 : RATE', 'RATE : RATE'],
	[F, T, 'part not indented', 'INDENT = 12', 'INDENT = 0'],
	[F, T, 'scale to the top only', 'var range = hi - lo || 1', 'var range = hi || 1'],
	[F, T, 'earned flush under the base', '\t\t\t\ty += 2;\n\t\t\t\trow += mark(s.earned.value', '\t\t\t\trow += mark(s.earned.value'],
	[F, T, 'negatives grow right', 'return _.bar(v < 0 ? z - w : z,', 'return _.bar(z,'],
	[F, T, 'negative bar square on the left', 'fill, op, c, v < 0);', 'fill, op, c, false);'],
	[F, T, 'zero line without negatives', 'if (lo < 0) {', 'if (lo <= 0) {'],
	[F, T, 'losses in brand colour', "var fill = loss ? 'currentColor' : pal.solid;", 'var fill = pal.solid;'],
	[F, T, 'loss opacity', 'loss ? 0.35 :', 'loss ? 0.5 :'],
	[F, T, 'loss earned opacity', 'loss ? 0.7 : 1,', 'loss ? 1 : 1,'],
	[F, T, 'no separator before losses', 'if (i && (s.gap || firstLoss))', 'if (i && s.gap)'],
	[F, T, 'a separator between losses', "firstLoss = loss && !(i && steps[i - 1].group === 'losses')", 'firstLoss = loss'],
	[F, T, 'a zero value draws a bar', "if (!w) return '';", ''],
	[F, T, 'null rate as blank', 's.rate === null ? DASH : s.rate', "s.rate === null ? '' : s.rate"],
	[F, T, 'null rate hidden', 'if (s.rate !== undefined) {', 'if (s.rate != null) {'],
	[F, T, 'earned value not bold', "_.el('tspan', ['font-weight', 600]", "_.el('tspan', ['font-weight', 400]"],
	[C, T, 'rows never split', 'var dy = chars * GLYPH > NARROW ? LINE : 0;', 'var dy = 0;'],
	[C, T, 'values on the label line when split', "'y', y + dy + 13, 'text-anchor', 'end'", "'y', y + 13, 'text-anchor', 'end'"],
	[C, T, 'glyph estimate narrower', 'NARROW = 343, GLYPH = 8;', 'NARROW = 343, GLYPH = 7;'],
	[C, T, 'labels never cut', 'label.length > max ?', 'false ?'],
	[C, T, 'part loses no characters', 'var max = Math.floor(NARROW / GLYPH) - (indent ? 2 : 0),', 'var max = Math.floor(NARROW / GLYPH),'],
	[F, T, 'funnel chars ignore earned', "(s.earned ? s.earned.display.length + 3 : 0) + 2", '2'],
	[F, T, 'part label not indented', 's.part ? INDENT : 0, y);', '0, y);'],
	[F, T, 'row without a title', "_.el('title', [], _.esc(tip))", "''"],
	[F, T, 'rate missing from the title', "tip += ' (' + rate + ')';", ''],
	[F, T, 'legend without earned', '\t\tif (earned) {', '\t\tif (opts.legend) {'],
	[F, T, 'legend base swatch solid', '[[opts.legend[0], pal.solid, pal.opacity]', '[[opts.legend[0], pal.solid, 1]'],
	[F, T, 'ghost on a part', 'prev.value > 0 && !s.part && !loss) {', 'prev.value > 0 && !loss) {'],
	[F, T, 'ghost follows parts', 'if (!s.part && !loss) prev = s;', 'if (!loss) prev = s;'],
	[F, T, 'shape not centred', 'return _.bar(50 - w / 2, w,', 'return _.bar(0, w,'],
	[C, T, 'root with a viewBox', "'width', '100%',\n\t\t\t'height'", "'viewBox', '0 0 100 100',\n\t\t\t'height'"],
	[C, T, 'root text size', "'font-size', 13,", "'font-size', 12,"],
	[C, T, 'bar overlap darker', "'fill', fill, 'opacity', opacity],", "'fill', fill, 'fill-opacity', opacity],"],
	[C, T, 'bar square side ignored', 'el(\'rect\', toLeft ?', 'el(\'rect\', false ?'],
	[C, T, 'legend lines tighter', 'top = y + i * 18;', 'top = y + i * 16;'],
	[C, T, 'light mark opacity', 'LIGHT = 0.6;', 'LIGHT = 0.55;'],
	[C, T, 'solid contrast target', 'bg, 4.5, t ===', 'bg, 3, t ==='],
	[C, T, 'contrast repaired the wrong way', "t === 'dark' ? 1 : -1);", "t === 'dark' ? -1 : 1);"],
	[C, T, 'no band clamp', 'var solid = fromOklch(Math.min(BAND[t][1], Math.max(BAND[t][0], o[0])), o[1], o[2] + (turn || 0));', 'var solid = fromOklch(o[0], o[1], o[2] + (turn || 0));'],
	[C, T, 'channel clipping instead of chroma', 'if (!inGamut(v)) {', 'if (false) {'],
	[C, T, 'default brand', "bg = rgb(SURFACE[t]), o = oklch(rgb(brand || '#2563eb'))", "bg = rgb(SURFACE[t]), o = oklch(rgb(brand || '#0066ff'))"],
	[C, T, 'the shade default brand', "var o = oklch(rgb(brand || '#2563eb'));", "var o = oklch(rgb(brand || '#0066ff'));"],
	[C, T, 'the hue turn ignored', 'o[2] + (turn || 0)', 'o[2]'],
	// the waterfall (M6, ADR 014)
	[W, T, 'waterfall without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-waterfall.js');", 'if (!core) return;'],
	[W, T, 'waterfall exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.waterfall;'],
	[W, T, 'waterfall steps may be any object', "if (!Array.isArray(steps)) fail('`steps` must be an array');", ''],
	[W, T, 'an empty waterfall accepted', "if (!steps.length) fail('no steps');", ''],
	[W, T, 'a first delta accepted', "else if (!i) fail('the first step must be a total');", ''],
	[W, T, 'kind unchecked', "else if (s.kind !== 'delta') fail(at + ': `kind` must be \"total\" or \"delta\"');", ''],
	[W, T, 'a null waterfall step reaches the engine', 'var s = steps[i] || {}', 'var s = steps[i]'],
	[W, T, 'waterfall overflow drawn as nothing', "if (!isFinite(hi - lo)) fail('values too far apart to share a scale');", ''],
	[W, T, 'a delta\'s length on the scale', 'lo = Math.min(lo, run);', 'lo = Math.min(lo, run, s.value);'],
	[W, T, 'waterfall scale to the top only', 'var range = hi - lo || 1', 'var range = hi || 1'],
	[W, T, 'no ghost', 'if (!total && run) row += span(', 'if (false) row += span('],
	[W, T, 'a ghost of a zero running total', 'if (!total && run) row', 'if (!total) row'],
	[W, T, 'ghost opacity', "span(0, run, 'currentColor', 0.12,", "span(0, run, 'currentColor', 0.2,"],
	[W, T, 'increase solid', 'pal.solid, pal.opacity, p', 'pal.solid, 1, p'],
	[W, T, 'decrease in the brand hue', 'Math.PI).solid', '0).solid'],
	[W, T, 'deltas from zero', 'from = total ? 0 : run', 'from = 0'],
	[W, T, 'the running total forgets deltas', 'run = total ? v : run + v;', 'run = v;'],
	[W, T, 'waterfall bar square on the wrong side', 'BAR, fill, op, cls, b < a);', 'BAR, fill, op, cls, false);'],
	[W, T, 'waterfall zero line without negatives', 'if (lo < 0) {', 'if (lo <= 0) {'],
	[W, T, 'a zero waterfall value draws a bar', 'if (v) {', 'if (true) {'],
	[W, T, 'waterfall row without a title', "_.el('title', [], _.esc(s.label + ': ' + s.display))", "''"],
	[W, T, 'waterfall title unescaped', "_.el('title', [], _.esc(s.label + ': ' + s.display))", "_.el('title', [], s.label + ': ' + s.display)"],
	[W, T, 'waterfall chars ignore the value', 's.label.length + s.display.length + 2', 's.label.length + 2'],
	[W, T, 'waterfall bar height', 'var BAR = 12, PAD = 10;', 'var BAR = 14, PAD = 10;'],
	[W, T, 'waterfall row padding', 'var BAR = 12, PAD = 10;', 'var BAR = 12, PAD = 8;'],
	[W, T, 'waterfall ids ignore the kind', ", _.str(s.display, at + ' display'), s.kind]);", ", _.str(s.display, at + ' display')]);"],
	[W, T, 'waterfall ids ignore the options', 'key.push([opts.title, opts.desc, opts.brand, opts.theme]);', ''],
	[W, BUNDLE, 'bundled: waterfall exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.waterfall;'],
	['charts-waterfall.d.ts', TYPES, 'kind is open', "kind: 'total' | 'delta';", 'kind: string;'],
	['charts-waterfall.d.ts', TYPES, 'kind optional', "kind: 'total' | 'delta';", "kind?: 'total' | 'delta';"],
	['charts-waterfall.d.ts', TYPES, 'waterfall global not merged', 'interface ChartsGlobal extends WaterfallApi {}', ''],
	['charts-waterfall.d.ts', TYPES, 'waterfall options take a form', 'type Options = Core.Common;', "type Options = Core.Common & { form?: 'bars' };"],
	// the series (M6 Group B, ADR 015)
	[S, T, 'series without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-series.js');", 'if (!core) return;'],
	[S, T, 'series exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.series;'],
	[S, BUNDLE, 'bundled: series exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.series;'],
	[S, T, 'series points may be any object', "if (!Array.isArray(points)) fail('`points` must be an array');", ''],
	[S, T, 'an empty series accepted', "if (!points.length) fail('no points');", ''],
	[S, T, 'three series accepted', 'names.length > 2', 'names.length > 3'],
	[S, T, 'series names unchecked', "for (var j = 0; j < names.length; j++) _.str(names[j], 'name ' + j);", ''],
	[S, T, 'series unknown form accepted', "form !== 'columns') fail('unknown form');", "form !== 'columns') form = 'line';"],
	[S, T, 'stacked lines accepted', "if (o.stacked && form !== 'columns') fail('`stacked` needs `columns`');", ''],
	[S, T, 'an area of two series accepted', "if (form === 'area' && names.length > 1) fail('`area` draws a single series');", ''],
	[S, T, 'format unchecked', "if (o.format != null && typeof o.format !== 'function') fail('`format` must be a function');", ''],
	[S, T, 'previous with two series accepted', "if (names.length > 1) fail('`previous` compares a single series');", ''],
	[S, T, 'previous length unchecked', "pair(prev.values, prev.display, points.length, 'previous', scan);", "pair(prev.values, prev.display, prev.values.length, 'previous', scan);"],
	[S, T, 'mismatched lengths accepted', 'values.length !== len || display.length !== len', 'values.length < len'],
	[S, T, 'a null value with a display accepted', "if (display[j] !== null) fail(at + ': a `null` value needs a `null` display');", ''],
	[S, T, 'a null point reaches the engine', 'var p = points[i] || {}', 'var p = points[i]'],
	[S, T, 'negative stack parts accepted', "if (v < 0) fail('a stack cannot hold a negative value');", ''],
	[S, T, 'a stack scaled by its parts', 'if (o.stacked) scan(sum);', 'if (o.stacked) scan(sum / 2);'],
	[S, T, 'previous left out of the scale', "'previous', scan);", "'previous', function () {});"],
	[S, T, 'series overflow drawn as nothing', "if (!isFinite(hi - lo)) fail('values too far apart to share a scale');", ''],
	[S, T, 'the scale leaves out zero', 'var names = o.names, form = o.form, lo = 0, hi = 0', 'var names = o.names, form = o.form, lo = Infinity, hi = -Infinity'],
	[S, T, 'ticks not nice', 'f <= 2 ? 2 : f <= 5 ? 5 : 10', 'f <= 2 ? 2 : f <= 5 ? 4 : 10'],
	[S, T, 'ticks keep float noise', '+(k * step).toPrecision(12)', 'k * step'],
	[S, T, 'a flat series gets two ticks', 'if (lo === hi) return [0];', 'if (lo === hi) return [0, 1];'],
	[S, T, 'tick text rounded to integers', 'return _.n(v, 6);', 'return _.n(v);'],
	[S, T, 'tick text unescaped', "_.esc(_.str(format(tk[i]), 'format(v)'))", "_.str(format(tk[i]), 'format(v)')"],
	[S, T, 'format may return a number', "_.str(format(tk[i]), 'format(v)')", 'String(format(tk[i]))'],
	[S, T, 'the zero gridline not stronger', 'tk[i] ? 0.12 : 0.35', '0.12'],
	[S, T, 'tick text under its gridline', "_.n(gy - 4, 2), 'opacity', 0.7", "_.n(gy + 12, 2), 'opacity', 0.7"],
	[S, T, 'points at band edges', 'function cx(i) { return off + (i + 0.5) * w; }', 'function cx(i) { return off + i * w; }'],
	[S, T, 'plot height', 'PLOT = 160', 'PLOT = 150'],
	[S, T, 'no room for the top tick', 'TOP = 16', 'TOP = 0'],
	[S, T, 'null bridged', 'if (i < N && values[i] !== null) {', 'if (i < N) {'],
	[S, T, 'a lone point dropped', 'if (run.length === 1) {', 'if (false) {'],
	[S, T, 'the stroke scales', "'vector-effect', 'non-scaling-stroke'", "'vector-effect', null"],
	[S, T, 'the area from the foot, not zero', "'L' + run.join('L') + 'L' +\n\t\t\t\t\t\t\trun[run.length - 1][0] + ',' + _.n(z, 2)", "'L' + run.join('L') + 'L' +\n\t\t\t\t\t\t\trun[run.length - 1][0] + ',' + PLOT"],
	[S, T, 'the area wash opaque', "'fill-opacity', 0.1", "'fill-opacity', 1"],
	[S, T, 'previous over the series', "if (prev) box += line(prev.values, 'currentColor', 0.35, p + '-prev');", ''],
	[S, T, 'previous at full strength', "line(prev.values, 'currentColor', 0.35,", "line(prev.values, 'currentColor', 1,"],
	[S, T, 'series 2 in the brand hue', '_.palette(o.brand, o.theme, Math.PI).solid', '_.palette(o.brand, o.theme).solid'],
	[S, T, 'the end dot on the last point, data or not', 'for (i = N - 1; i >= 0 && vs[i] === null; i--);', 'i = N - 1; if (vs[i] === null) i = -1;'],
	[S, T, 'the surface ignores the theme', "_.SURFACE[o.theme === 'dark' ? 'dark' : 'light']", '_.SURFACE.light'],
	[S, T, 'the end dot without a ring', "'fill', colour[j], 'stroke', surface, 'stroke-width', 2]", "'fill', colour[j]]"],
	[S, T, 'tick text under the marks', "'overflow', 'visible'], box) + dots + tickText;", "'overflow', 'visible'], tickText + box) + dots;"],
	[S, T, 'tick text without a halo', "'paint-order', 'stroke'", "'paint-order', null"],
	[S, T, 'the key shows the first value', 'var d = cur ? last.display[j]', 'var d = cur ? points[0].display[j]'],
	[S, T, 'the key without the comparison', 'var cur = j < S, name = cur ? names[j] : prev && prev.name;', 'var cur = j < S, name = cur ? names[j] : null;'],
	[S, T, 'a missing last value left blank', "d = d == null ? '—' : d;", "d = d == null ? '' : d;"],
	[S, T, 'the key ignores the value length', 'name.length + d.length + 4', 'name.length + 4'],
	[S, T, 'grouped columns overlap', 'j * (cw + g)', 'j * cw * 0.5'],
	[S, T, 'grouped columns without a gap', 'g = S > 1 && !o.stacked ? 0.06 * w : 0', 'g = 0'],
	[S, T, 'columns past 24px', 'GLYPH = 8, COL = 24;', 'GLYPH = 8, COL = 30;'],
	[S, T, 'the column viewport the whole band', "return _.el('svg', ['x', _.pct(x), 'width', _.pct(cw)], inner);", "return _.el('svg', ['x', _.pct(x), 'width', _.pct(w)], inner);"],
	// the zero-step guard: without it the tick loop pushes until the array overflows — tens of GB — so its gate
	// caps the heap at 128 MB and the test process dies in under a second (measured)
	[S, CAPPED, 'a zero step loops', 'if (!(step > 0)) return t;', 'if (step !== step) return t;'],
	[S, T, 'a tick span that overflows drawn', 'if (!isFinite(tk[tk.length - 1] - tk[0])) fail', 'if (false) fail'],
	[SK, T, 'an underflowing link drawn', "if (!(h > 0)) fail('flows too far apart to draw');", ''],
	[MT, T, 'meter ids ignore the marks', 'marks.map(function (q) { return q.value; }), out', 'out'],
	[C, T, 'null options accepted', 'var o = options === undefined ? {} : options;', 'var o = options == null ? {} : options;'],
	[C, T, 'a null title accepted', "if (o.title !== undefined) str(o.title, 'title');", "if (o.title != null) str(o.title, 'title');"],
	[S, T, 'a zero column drawn', 'if (!v) continue;', 'if (v === null) continue;'],
	[S, T, 'stacked parts touch', 'Math.max(b, at(base) - 2)', 'Math.max(b, at(base))'],
	[S, T, 'every stacked part rounded', 'colour[j], topmost);', 'colour[j], true);'],
	[S, T, 'stacked parts from zero', 'base += v;', ''],
	[S, T, 'a column square at the data end', "b < a ? _.n(h - r, 2) : 0", "b < a ? 0 : _.n(h - r, 2)"],
	[S, T, 'x labels: only the first and the last', 'm < N - 1; m += step', 'm < 0; m += step'],
	[S, T, 'x labels may touch the last', 'c + half + 12 <= lastLeft', 'c - half <= lastLeft'],
	[S, T, 'x labels: the edge ones always at the edge', 'if (len <= bw2) {', 'if (false) {'],
	[S, T, 'x labels spaced by the shortest', 'maxLen = Math.max(maxLen, points[i].x.length)', 'maxLen = 1'],
	[S, T, 'no hover bands', "out += _.el('rect', ['class', p + '-hit'", "out += ''; void _.el('rect', ['class', p + '-hit'"],
	[S, T, 'hover title leaves out the comparison', "if (prev) t.push(prev.name + ' ' + (prev.display[i] == null ? '—' : prev.display[i]));", ''],
	[S, T, 'hover title unescaped', "_.el('title', [], _.esc(points[i].x + ': ' + t.join(', ')))", "_.el('title', [], points[i].x + ': ' + t.join(', '))"],
	[S, T, 'series ids ignore what is drawn', 'opts.previous && opts.previous.values, d.body])', 'opts.previous && opts.previous.values])'],
	[S, T, 'series ids ignore the values', 'points.map(function (q) { return q.values; }), opts.previous', 'opts.previous'],
	// the caller's second colour and gutter (ADR 021)
	[S, T, 'second ignored', ': o.second ? _.palette(o.second, o.theme).solid : _.palette', ': _.palette'],
	[S, T, 'second not fitted', 'o.second ? _.palette(o.second, o.theme).solid', 'o.second ? o.second'],
	[S, T, 'tint is the solid', "o.second === 'tint' ? pal.light", "o.second === 'tint' ? pal.solid"],
	[S, T, 'tint fitted as a hex', "o.second === 'tint' ? pal.light", "o.second === 'tint' ? _.palette(pal.light, o.theme).solid"],
	[S, T, 'tint rejected', "if (o.second !== 'tint' && (", 'if (('],
	[S, T, 'second unchecked', "if (o.second !== 'tint' && (typeof o.second !== 'string' || !/^#[0-9a-fA-F]{6}$/.test(o.second))) fail", 'if (false) fail'],
	[S, T, 'second with one series accepted', "if (names.length < 2) fail('`second` colours a second series');", ''],
	[S, T, 'gutter unchecked', "if (o.gutter !== undefined && (typeof o.gutter !== 'number' || !(o.gutter >= 0 && o.gutter <= 50))) fail", 'if (false) fail'],
	[S, T, 'gutter may be NaN', '!(o.gutter >= 0 && o.gutter <= 50)', '(o.gutter < 0 || o.gutter > 50)'],
	[S, T, 'gutter past half accepted', 'o.gutter <= 50', 'o.gutter <= 100'],
	[S, T, 'bands over the gutter', 'w = (100 - off) / N', 'w = 100 / N'],
	[S, T, 'points ignore the gutter', 'return off + (i + 0.5) * w;', 'return (i + 0.5) * w;'],
	[S, T, 'columns ignore the gutter', 'out += view(off + i * w + 0.15 * w + j * (cw + g)', 'out += view(i * w + 0.15 * w + j * (cw + g)'],
	[S, T, 'stacks ignore the gutter', 'if (stack) out += view(off + i * w + 0.15 * w, stack);', 'if (stack) out += view(i * w + 0.15 * w, stack);'],
	[S, T, 'hover bands ignore the gutter', "'x', _.pct(off + i * w)", "'x', _.pct(i * w)"],
	[S, T, 'the first x label at the chart edge', "end ? '100%' : off ? _.pct(off) : 0", "end ? '100%' : 0"],
	[S, T, 'x labels spaced over the whole width', 'plot = NARROW * (100 - off) / 100', 'plot = NARROW'],
	['charts-series.d.ts', TYPES, 'gutter typed loosely', 'gutter?: number;', 'gutter?: number | string;'],
	['charts-series.d.ts', TYPES, 'second untyped', 'second?: string;', ''],
	['charts-series.d.ts', TYPES, 'series names unbounded', 'names: [string] | [string, string];', 'names: string[];'],
	['charts-series.d.ts', TYPES, 'series names optional', 'names: [string] | [string, string];', 'names?: [string] | [string, string];'],
	['charts-series.d.ts', TYPES, 'series form open', "form?: 'line' | 'area' | 'columns';", 'form?: string;'],
	['charts-series.d.ts', TYPES, 'previous a bare array', 'previous?: Previous;', 'previous?: Previous | number[];'],
	['charts-series.d.ts', TYPES, 'series global not merged', 'interface ChartsGlobal extends SeriesApi {}', ''],
	// the sparkline and the tile (M6 Group B, ADR 016)
	[K, T, 'spark without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-spark.js');", 'if (!core) return;'],
	[K, T, 'the tile not registered', 'core.tile = api.tile;', ''],
	[K, BUNDLE, 'bundled: spark exports its functions', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = api;'],
	[K, T, 'spark values may be any object', "if (!Array.isArray(values) || !values.length) fail", 'if (!values) fail'],
	[K, T, 'an empty spark accepted', '!Array.isArray(values) || !values.length', '!Array.isArray(values)'],
	[K, T, 'spark values unchecked', "_.num(values[i], what + ' ' + i);", ''],
	[K, T, 'spark overflow drawn as nothing', "if (hi > lo && !isFinite(hi - lo)) fail('values too far apart to share a scale');", ''],
	[K, T, 'the spark scale from zero', 'return hi > lo ? (hi - v) / (hi - lo) * h : h / 2;', 'return hi > 0 ? (hi - v) / hi * h : h / 2;'],
	[K, T, 'equal values at the foot', ': h / 2; }', ': h; }'],
	[K, T, 'spark points at band edges', 'function cx(i) { return (i + 0.5) * 100 / N; }', 'function cx(i) { return i * 100 / N; }'],
	[K, T, 'spark null bridged', 'if (i < N && values[i] !== null) { run.push', 'if (i < N) { run.push'],
	[K, T, 'a lone spark point dropped', 'if (run.length === 1) {', 'if (false) {'],
	[K, T, 'the spark stroke scales', "'vector-effect', 'non-scaling-stroke'", "'vector-effect', null"],
	[K, T, 'no end dot', 'if (last >= 0) {', 'if (false) {'],
	[K, T, 'the end dot without a ring', "'fill', dot, 'stroke', surface, 'stroke-width', 2]", "'fill', dot]"],
	[K, T, 'the spark box at the top edge', 'var H = 32, PAD = 6', 'var H = 32, PAD = 0'],
	[K, T, 'the surface ignores the theme', "_.SURFACE[o.theme === 'dark' ? 'dark' : 'light']", '_.SURFACE.light'],
	[K, T, 'spark ids ignore the values', 'JSON.stringify([o.title, o.desc, values, body])', 'JSON.stringify([o.title, o.desc, body])'],
	[K, T, 'tile ids ignore the trend', 'JSON.stringify([o.title, o.desc, t.trend, out])', 'JSON.stringify([o.title, o.desc, out])'],
	[K, T, 'a tile may be a string', "if (!t || typeof t !== 'object') fail('the tile must be an object');", "if (!t) fail('the tile must be an object');"],
	[K, T, 'the value may be a number', "_.str(t.value, 'value');", ''],
	[K, T, 'a delta may be a string', "if (typeof d !== 'object') fail('`delta` must be an object');", ''],
	[K, T, 'a delta without display', "_.str(d.display, 'delta display');", ''],
	[K, T, 'any direction', "if (d.direction !== 'up' && d.direction !== 'down' && d.direction !== 'flat') fail", 'if (false) fail'],
	[K, T, 'up without good', "if (d.direction !== 'flat' && typeof d.good !== 'boolean') fail", 'if (false) fail'],
	[K, T, 'trend unchecked', "if (t.trend != null) check(t.trend, 'trend');", ''],
	[K, T, 'the label never cut', 'label.length > LABEL ?', 'false ?'],
	[K, T, 'the label cut at 30', 'LABEL = 20', 'LABEL = 30'],
	[K, T, 'a cut label without its title', "_.el('title', [], _.esc(label)) + _.esc(label.slice(0, cut) + '…')", "_.esc(label.slice(0, cut) + '…')"],
	[K, T, 'a cut label splits an emoji', 'if (c >= 0xD800 && c <= 0xDBFF) cut--;', ''],
	[K, T, 'the value small', "'font-size', 26, 'font-weight', 600", "'font-size', 20, 'font-weight', 600"],
	[K, T, 'the delta in the value colour', "'fill', flat ? null : _.palette(d.good ? GOOD : BAD, o.theme).solid", "'fill', null"],
	[K, T, 'colour by direction, not good', '_.palette(d.good ? GOOD : BAD, o.theme)', "_.palette(d.direction === 'up' ? GOOD : BAD, o.theme)"],
	[K, T, 'a change without its arrow', "(flat ? '' : d.direction === 'up' ? '▲ ' : '▼ ')", "''"],
	[K, T, 'the arrow says good, not the direction', "d.direction === 'up' ? '▲ ' : '▼ '", "d.good ? '▲ ' : '▼ '"],
	[K, T, 'flat drawn as a change', "var flat = d.direction === 'flat';", 'var flat = false;'],
	[K, T, 'the trend in the brand', "trace(p, t.trend, y + 4, 'currentColor', 0.35,", "trace(p, t.trend, y + 4, _.palette(o.brand, o.theme).solid, 1,"],
	[K, T, 'the current period not in the accent', "0.35, _.palette(o.brand, o.theme).solid, surfaceOf(o))", "0.35, 'currentColor', surfaceOf(o))"],
	[K, T, 'no gap before the trend', 'y += 4 + H;', 'y += H;'],
	['charts-spark.d.ts', TYPES, 'good optional on up and down', "| { display: string; direction: 'up' | 'down'; good: boolean }", "| { display: string; direction: 'up' | 'down'; good?: boolean }"],
	['charts-spark.d.ts', TYPES, 'direction open', "| { display: string; direction: 'flat' };", '| { display: string; direction: string };'],
	['charts-spark.d.ts', TYPES, 'the value may be a number', 'value: string;', 'value: string | number;'],
	['charts-spark.d.ts', TYPES, 'spark takes anything', 'spark(values: (number | null)[], options?: Spark.Options): string;', 'spark(values: unknown[], options?: Spark.Options): string;'],
	['charts-spark.d.ts', TYPES, 'spark global not merged', 'interface ChartsGlobal extends SparkApi {}', ''],
	// the ranking (M7 Group C)
	[RK, T, 'rank without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-rank.js');", 'if (!core) return;'],
	[RK, BUNDLE, 'bundled: rank exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.rank;'],
	[RK, T, 'rank rows may be any object', "if (!Array.isArray(rows)) fail('`rows` must be an array');", ''],
	[RK, T, 'an empty ranking accepted', "if (!rows.length) fail('no rows');", ''],
	[RK, T, 'a null row reaches the engine', 'r = rows[i] || {};', 'r = rows[i];'],
	[RK, T, 'rank labels unchecked', "_.str(r.label, 'row ' + i + ' label');", ''],
	[RK, T, 'rank overflow drawn as nothing', "if (!isFinite(hi - lo)) fail('values too far apart to share a scale');", ''],
	[RK, T, 'highlight unchecked', "if (h != null && !(typeof h === 'number' && h >= 0 && h < rows.length && h % 1 === 0)) fail('`highlight` must be the index of a row');", ''],
	[RK, T, 'a string highlight accepted', "typeof h === 'number' && ", ''],
	[RK, T, 'a highlight past the rows accepted', 'h < rows.length', 'h <= rows.length'],
	[RK, T, 'rank scale to the top only', 'range = hi - lo || 1', 'range = hi || 1'],
	[RK, T, 'rank negatives grow right', 'r.value < 0 ? z - w : z', 'z'],
	[RK, T, 'a zero rank value draws a bar', 'if (r.value) {', 'if (true) {'],
	[RK, T, 'highlight index 0 ignored', 'muted = h != null && h !== i', 'muted = !!h && h !== i'],
	[RK, T, 'muted bars at full strength', "muted ? 0.35 : 1,", '1,'],
	[RK, T, 'muted bars in the brand', "muted ? 'currentColor' : solid", 'solid'],
	[RK, T, 'rank zero line without negatives', 'if (lo < 0) {', 'if (lo <= 0) {'],
	[RK, T, 'rank row without a title', "_.el('title', [], _.esc(r.label + ': ' + r.display))", "''"],
	[RK, T, 'rank chars ignore the value', 'r.label.length + r.display.length + 2', 'r.label.length + 2'],
	[RK, T, 'rank bar height', 'var BAR = 12, PAD = 10;', 'var BAR = 14, PAD = 10;'],
	[RK, T, 'rank ids ignore what is drawn', 'return q.value; }), out])', 'return q.value; })])'],
	[RK, T, 'rank ids ignore the values', 'rows.map(function (q) { return q.value; }), out', 'out'],
	['charts-rank.d.ts', TYPES, 'highlight any', 'highlight?: number;', 'highlight?: number | string;'],
	['charts-rank.d.ts', TYPES, 'display optional', '\t\tdisplay: string;', '\t\tdisplay?: string;'],
	['charts-rank.d.ts', TYPES, 'rank global not merged', 'interface ChartsGlobal extends RankApi {}', ''],
	// part to whole (M7 Group C, ADR 017)
	[SH, T, 'share without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-share.js');", 'if (!core) return;'],
	[SH, BUNDLE, 'bundled: share exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.share;'],
	[SH, T, 'share parts may be any object', "if (!Array.isArray(parts)) fail('`parts` must be an array');", ''],
	[SH, T, 'seven parts accepted', 'parts.length > 6', 'parts.length > 7'],
	[SH, T, 'no parts accepted', '!parts.length || parts.length > 6', 'parts.length > 6'],
	[SH, T, 'share unknown form accepted', "if (o.form != null && o.form !== 'bar' && o.form !== 'donut') fail('unknown form');", ''],
	[SH, T, 'a null part reaches the engine', 's = parts[i] || {};', 's = parts[i];'],
	[SH, T, 'share displays unchecked', "_.str(s.display, 'part ' + i + ' display');", ''],
	[SH, T, 'a negative part accepted', "if (_.num(s.value, 'part ' + i + ' value') < 0) fail('part ' + i + ' is negative: a share cannot be');", "_.num(s.value, 'part ' + i + ' value');"],
	[SH, T, 'share overflow drawn as nothing', "if (!isFinite(sum)) fail('the parts overflow a number');", ''],
	[SH, T, 'all zero accepted', "if (!sum) fail('every part is zero: nothing to share');", ''],
	[SH, T, 'the slots in the brand', 'fill = SLOTS[t][i]', 'fill = _.palette(o.brand, o.theme).solid'],
	[SH, T, 'the slots ignore the theme', "t = o.theme === 'dark' ? 'dark' : 'light'", "t = 'light'"],
	[SH, T, 'slots by the drawn parts, not the index', "'#d95926', '#199e70', '#c98500', '#d55181', '#008300']", "'#199e70', '#d95926', '#c98500', '#d55181', '#008300']"],
	[SH, T, 'a zero part drawn', 'if (f) {', 'if (true) {'],
	[SH, T, 'bar gaps at the edges too', "if (!donut && at) gaps +=", 'if (!donut) gaps +='],
	[SH, T, 'no bar gaps', 'marks += gaps;', ''],
	[SH, T, 'a gap line 1px', "'stroke', surface, 'stroke-width', 2]);", "'stroke', surface, 'stroke-width', 1]);"],
	[SH, T, 'the donut without gaps', '_.n(Math.max(f * CIRC - GAP, 0.5), 3)', '_.n(Math.max(f * CIRC, 0.5), 3)'],
	[SH, T, 'a sliver vanishes', 'Math.max(f * CIRC - GAP, 0.5)', 'Math.max(f * CIRC - GAP, 0)'],
	[SH, T, 'the donut parts all from 12 o\'clock', "'stroke-dashoffset', n > 1 ? _.n(-at * CIRC, 3) : null", "'stroke-dashoffset', n > 1 ? 0 : null"],
	[SH, T, 'the donut counter-clockwise', "_.n(-at * CIRC, 3)", '_.n(at * CIRC, 3)'],
	[SH, T, 'the donut from 3 o\'clock', "'transform', 'rotate(-90 50 50)'", "'transform', null"],
	[SH, T, 'one part dashed', "'stroke-dasharray', n > 1 ?", "'stroke-dasharray', n > 0 ?"],
	[SH, T, 'a part without its title', "title = _.el('title', [], _.esc(s.label + ': ' + s.display));", "title = '';"],
	[SH, T, 'the key with no space', 'BAR = 24, DONUT = 160, SPACE = 12', 'BAR = 24, DONUT = 160, SPACE = 0'],
	[SH, T, 'the key swatch in the wrong slot', "'rx', 2, 'fill', SLOTS[t][i]]", "'rx', 2, 'fill', SLOTS[t][0]]"],
	[SH, T, 'the key ignores the value length', 's.label.length + s.display.length + 4', 's.label.length + 4'],
	[SH, T, 'share ids ignore the values', 'parts.map(function (q) { return q.value; }), body]', 'body]'],
	['charts-share.d.ts', TYPES, 'share form open', "form?: 'bar' | 'donut';", 'form?: string;'],
	['charts-share.d.ts', TYPES, 'share display optional', '\t\tdisplay: string;', '\t\tdisplay?: string;'],
	['charts-share.d.ts', TYPES, 'share global not merged', 'interface ChartsGlobal extends ShareApi {}', ''],
	// the heatmap and the cohort (M7 Group C, M8, ADR 018)
	[HM, T, 'heatmap without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-heatmap.js');", 'if (!core) return;'],
	[HM, BUNDLE, 'bundled: heatmap exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.heatmap;'],
	[HM, T, 'heatmap unknown form accepted', "if (o.form != null && o.form !== 'grid' && !cohort) fail('unknown form');", ''],
	[HM, T, 'heatmap format unchecked', "if (o.format != null && typeof o.format !== 'function') fail('`format` must be a function');", ''],
	[HM, T, 'cells may be anything', "if (!cells || typeof cells !== 'object') fail('`cells` must be an object');", "if (!cells) fail('`cells` must be an object');"],
	[HM, T, 'empty labels accepted', "if (!Array.isArray(a) || !a.length) fail", 'if (!Array.isArray(a)) fail'],
	[HM, T, 'labels unchecked', "for (var i = 0; i < a.length; i++) _.str(a[i], what + ' ' + i);", ''],
	[HM, T, 'row count unchecked', '|| V.length !== rows.length || D.length !== rows.length', ''],
	[HM, T, 'display row length unchecked', '|| d.length !== v.length) fail', ') fail'],
	[HM, T, 'a long row accepted', 'if (v.length > cols.length || !cohort', 'if (!cohort'],
	[HM, T, 'a short grid row accepted', ' || !cohort && v.length < cols.length', ''],
	[HM, T, 'a null with a display accepted', "if (d[c] !== null) fail('row ' + r + ': a `null` value needs a `null` display');", ''],
	[HM, T, 'heatmap negatives accepted', "if (_.num(v[c], 'row ' + r + ' value') < 0) fail('row ' + r + ': a negative value has no step on a sequential ramp');", "_.num(v[c], 'row ' + r + ' value');"],
	[HM, T, 'heatmap displays unchecked', "_.str(d[c], 'row ' + r + ' display');", ''],
	[HM, T, 'the ramp ignores the theme', "t = o.theme === 'dark' ? 'dark' : 'light'", "t = 'light'"],
	[HM, T, 'a ramp step off', 'light: [0.71, 0.63, 0.55, 0.47, 0.39]', 'light: [0.71, 0.63, 0.59, 0.47, 0.39]'],
	[HM, T, 'steps by rounding', 'Math.min(4, Math.floor(v / max * 5))', 'Math.min(4, Math.round(v / max * 4))'],
	[HM, T, 'the max beyond the top step', 'Math.min(4, Math.floor(v / max * 5))', 'Math.floor(v / max * 5)'],
	[HM, T, 'all zero divides by zero', 'var s = max ? Math.min', 'var s = 1 ? Math.min'],
	[HM, T, 'null drawn as near zero', 'if (v === null) {', 'if (v === null && false) {'],
	[HM, T, 'the null dash lost', "'pointer-events', 'none'], '—');", "'pointer-events', 'none'], '');"],
	[HM, T, 'cohort text everywhere', 'if (cohort && d.length * SMALL + 4 <= bw) {', 'if (cohort) {'],
	[HM, T, 'grid text too', 'if (cohort && d.length * SMALL + 4 <= bw) {', 'if (d.length * SMALL + 4 <= bw) {'],
	[HM, T, 'cell text always white', "STEPS[t][s] >= 0.6 ? INK : '#fff'", "'#fff'"],
	[HM, T, 'cell text takes the hover', "'fill', STEPS[t][s] >= 0.6 ? INK : '#fff',\n\t\t\t\t\t\t\t'pointer-events', 'none']", "'fill', STEPS[t][s] >= 0.6 ? INK : '#fff']"],
	[HM, T, 'a cell without its title', "title = _.el('title', [], _.esc(rows[r] + ' · ' + cols[c] + ': ' + (d === null ? '—' : d)));", "title = '';"],
	[HM, T, 'gaps at the edges too', 'if (c) gaps +=', 'gaps +='],
	[HM, T, 'no gaps', "ll.svg + row + gaps);", 'll.svg + row);'],
	[HM, T, 'heatmap rows without their class', "_.el('g', ['class', p + '-row'], ll.svg", "_.el('g', [], ll.svg"],
	[HM, T, 'rows packed', 'y += CELL + PAD;', 'y += CELL;'],
	[HM, T, 'column labels: only the edges', 'm < N - 1; m += step', 'm < 0; m += step'],
	[HM, T, 'column labels by the shortest', 'maxLen = Math.max(maxLen, cols[i].length)', 'maxLen = 1'],
	[HM, T, 'the edge labels always at the edges', 'if (len <= bw) {', 'if (false) {'],
	[HM, T, 'the scale without its max', "_.esc(_.str(format(max), 'format(v)'))", "''"],
	[HM, T, 'scale text unescaped', "_.esc(_.str(format(0), 'format(v)'))", "_.str(format(0), 'format(v)')"],
	[HM, T, 'the default format rounds', 'return _.n(x, 6);', 'return _.n(x);'],
	[HM, T, 'heatmap ids ignore the values', 'JSON.stringify([o.title, o.desc, V, out])', 'JSON.stringify([o.title, o.desc, out])'],
	[C, T, 'shade ignores the lightness', 'return toHex(fromOklch(L, o[1], o[2]));', 'return toHex(fromOklch(0.55, o[1], o[2]));'],
	['charts-heatmap.d.ts', TYPES, 'heatmap form open', "form?: 'grid' | 'cohort';", 'form?: string;'],
	['charts-heatmap.d.ts', TYPES, 'heatmap display optional', 'display: (string | null)[][];', 'display?: (string | null)[][];'],
	['charts-heatmap.d.ts', TYPES, 'heatmap global not merged', 'interface ChartsGlobal extends HeatmapApi {}', ''],
	// the meter (M8 Group D)
	[MT, T, 'meter without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-meter.js');", 'if (!core) return;'],
	[MT, BUNDLE, 'bundled: meter exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.meter;'],
	[MT, T, 'a meter may be a string', "if (!m || typeof m !== 'object') fail('the meter must be an object');", "if (!m) fail('the meter must be an object');"],
	[MT, T, 'the target display unchecked', "td = _.str(m.targetDisplay, 'targetDisplay')", 'td = m.targetDisplay'],
	[MT, T, 'a negative value accepted', "if (_.num(m.value, 'value') < 0) fail('`value` cannot be negative');", "_.num(m.value, 'value');"],
	[MT, T, 'a zero target accepted', "if (!(_.num(m.target, 'target') > 0)) fail('`target` must be above zero');", "_.num(m.target, 'target');"],
	[MT, T, 'marks may be any object', "if (!Array.isArray(marks)) fail('`marks` must be an array');", ''],
	[MT, T, 'a null mark reaches the engine', 'k = marks[i] || {};', 'k = marks[i];'],
	[MT, T, 'mark labels unchecked', "_.str(k.label, 'mark ' + i + ' label');", ''],
	[MT, T, 'a mark at zero accepted', "_.num(k.value, 'mark ' + i + ' value') > 0 &&", "_.num(k.value, 'mark ' + i + ' value') >= 0 &&"],
	[MT, T, 'a mark past the target accepted', '&& k.value <= m.target)', ')'],
	[MT, T, 'the fill past the track', 'Math.min(1, m.value / m.target) * 100', 'm.value / m.target * 100'],
	[MT, T, 'a zero fill drawn', "(f ? _.bar(0, f, y, BAR, solid, 1, p + '-bar') : '')", "_.bar(0, f, y, BAR, solid, 1, p + '-bar')"],
	[MT, T, 'the track at full strength', 'TRACK = 0.2', 'TRACK = 1'],
	[MT, T, 'marks inside the bar only', "'y1', y - 3, 'y2', y + BAR + 3", "'y1', y, 'y2', y + BAR"],
	[MT, T, 'marks at the value, not the target', 'marks[i].value / m.target * 100', 'marks[i].value / m.value * 100'],
	[MT, T, 'a mark without its title', "_.el('title', [], _.esc(marks[i].label)));", "'');"],
	[MT, T, 'the bar without its title', "_.el('title', [], _.esc(label + ': ' + display + ' / ' + td))", "''"],
	[MT, T, 'the target unescaped', "'opacity', 0.7], _.esc(td));", "'opacity', 0.7], td);"],
	[MT, T, 'meter chars ignore the value', 'label.length + display.length + 2', 'label.length + 2'],
	[MT, T, 'meter ids ignore what is drawn', 'return q.value; }), out]))', 'return q.value; })]))'],
	[MT, T, 'meter ids ignore the values', 'm.value, m.target, marks', 'marks'],
	['charts-meter.d.ts', TYPES, 'target display optional', '\t\ttargetDisplay: string;', '\t\ttargetDisplay?: string;'],
	['charts-meter.d.ts', TYPES, 'mark label optional', '\t\tlabel: string;\n\t}\n\n\tinterface Meter {', '\t\tlabel?: string;\n\t}\n\n\tinterface Meter {'],
	['charts-meter.d.ts', TYPES, 'meter global not merged', 'interface ChartsGlobal extends MeterApi {}', ''],
	// the sankey (M8 Group D, ADR 019)
	[SK, T, 'sankey without core does not throw', "if (!core || !core._) throw new Error('affiliate-charts: load charts.js before charts-sankey.js');", 'if (!core) return;'],
	[SK, BUNDLE, 'bundled: sankey exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.sankey;'],
	[SK, T, 'sankey nodes may be any object', "if (!Array.isArray(nodes)) fail('`nodes` must be an array');", ''],
	[SK, T, 'sankey links may be any object', "if (!Array.isArray(links)) fail('`links` must be an array');", ''],
	[SK, T, 'a null node reaches the engine', 'n = nodes[i] || {};', 'n = nodes[i];'],
	[SK, T, 'repeated ids accepted', "if (byId['#' + _.str(n.id, at + ' id')]) fail(at + ': its id repeats an earlier node\\'s');", "_.str(n.id, at + ' id');"],
	[SK, T, 'ids without their prefix', "byId['#' + n.id] = a =", 'byId[n.id] = a ='],
	[SK, T, 'a fractional column accepted', 'n.column % 1 || ', ''],
	[SK, T, 'a string column accepted', "typeof n.column !== 'number' || ", ''],
	[SK, T, 'five columns accepted', 'n.column < 0 || n.column > 3', 'n.column < 0 || n.column > 4'],
	[SK, T, 'a long short tag accepted', 'chars > 3', 'chars > 4'],
	[SK, T, 'an empty short tag accepted', '!chars || ', ''],
	[SK, T, 'short tags counted in UTF-16 units', ".replace(/[\\uD800-\\uDBFF][\\uDC00-\\uDFFF]/g, '_').length", '.length'],
	[SK, T, 'sankey labels unchecked', "_.str(n.label, at + ' label');", ''],
	[SK, T, 'one column accepted', "if (C < 2) fail('two to four columns');", ''],
	[SK, T, 'a skipped column accepted', "if (!cols[c]) fail('column ' + c + ' has no node');", 'if (!cols[c]) continue;'],
	[SK, T, 'nine nodes accepted', 'cols[c].length > 8', 'cols[c].length > 9'],
	[SK, T, 'a null link reaches the engine', 'l = links[i] || {};', 'l = links[i];'],
	[SK, T, 'unknown nodes accepted', "if (!a || !b) fail(at + ': unknown node');", ''],
	[SK, T, 'links may skip or go back', "if (b.c !== a.c + 1) fail(at + ': a link joins a column to the next');", ''],
	[SK, T, 'negative links accepted', "if (_.num(l.value, at + ' value') < 0) fail(at + ' is negative');", "_.num(l.value, at + ' value');"],
	[SK, T, 'sankey link displays unchecked', "_.str(l.display, at + ' display');", ''],
	[SK, T, 'sankey overflow drawn as nothing', "if (!isFinite(a.out) || !isFinite(b.inn)) fail('the flows overflow a number');", ''],
	[SK, T, 'nothing flowing accepted', "if (!any) fail('every link is zero: nothing flows');", ''],
	[SK, T, 'a node only its inflow', 'a.size = Math.max(a.inn, a.out);', 'a.size = a.inn || a.out;'],
	[SK, T, 'the scale by the emptiest column', 'k = Math.min(k, (H - (count - 1) * GAP) / sum)', 'k = (H - (count - 1) * GAP) / sum'],
	[SK, T, 'zero nodes take a gap', 'if (a.size) count++;', 'count++;'],
	[SK, T, 'nodes packed', 'y += a.h + GAP;', 'y += a.h;'],
	[SK, T, 'ribbons stack from the top', 'a.o += h;', ''],
	[SK, T, 'ribbons land stacked from the top', 'b.i += h;', ''],
	[SK, T, 'a zero link drawn', 'if (!l.value) continue;', ''],
	[SK, T, 'straight ribbons', "var h = l.value * k, x0 = _.n(x(a.c), 3), x1 = _.n(x(b.c), 3), xm = _.n((x(a.c) + x(b.c)) / 2, 3);", "var h = l.value * k, x0 = _.n(x(a.c), 3), x1 = _.n(x(b.c), 3), xm = x0;"],
	[SK, T, 'ribbons opaque', 'LINK = 0.3', 'LINK = 1'],
	[SK, T, 'nodes at the edge spill out', "'transform', shift ? 'translate(-' + _.n(shift, 2) + ')' : null", "'transform', null"],
	[SK, T, 'tags outward at the last column', "'dx', last ? -NODE - 4 :", "'dx', last ? NODE + 4 :"],
	[SK, T, 'tags not centred on their node', "_.n(TOP + a.y + a.h / 2 + 4, 2)", "_.n(TOP + a.y + 4, 2)"],
	[SK, T, 'tags without a halo', "'paint-order', 'stroke'], _.esc(a.n.short))", "'paint-order', null], _.esc(a.n.short))"],
	[SK, T, 'tags unescaped', '_.esc(a.n.short)', 'a.n.short'],
	[SK, T, 'no room above the plot', 'var TOP = 8,', 'var TOP = 0,'],
	[SK, T, 'a ribbon without its title', "title(a.n.label + ' → ' + b.n.label + ': ' + l.display)", "''"],
	[SK, T, 'a node without its title', "title(a.n.label + ': ' + a.n.display)", "''"],
	[SK, T, 'the key without the tag', "var name = n.short + ' ' + n.label", 'var name = n.label'],
	[SK, T, 'the key ignores the display length', 'name.length + n.display.length + 2', 'name.length + 2'],
	[SK, T, 'sankey ids ignore the flows', 'links.map(function (q) { return q.value; }), out]', 'out]'],
	['charts-sankey.d.ts', TYPES, 'short optional', '\t\tshort: string;', '\t\tshort?: string;'],
	['charts-sankey.d.ts', TYPES, 'link display optional', '\t\tvalue: number;\n\t\tdisplay: string;', '\t\tvalue: number;\n\t\tdisplay?: string;'],
	['charts-sankey.d.ts', TYPES, 'sankey global not merged', 'interface ChartsGlobal extends SankeyApi {}', ''],
	[F, BUNDLE, 'bundled: module exports the function', 'if (cjs) module.exports = core;', 'if (cjs) module.exports = core.funnel;'],
	[F, BUNDLE, 'bundled: the core taken from a global', "var core = cjs ? require('./charts.js') : root.Charts;", 'var core = root.Charts;'],
	['charts-funnel.d.ts', TYPES, 'form is open', "form?: 'bars' | 'steps' | 'shape';", 'form?: string;'],
	['charts-funnel.d.ts', TYPES, 'legend not a pair', 'legend?: [string, string];', 'legend?: string[];'],
	['charts-funnel.d.ts', TYPES, 'group is open', "group?: 'losses';", 'group?: string;'],
	['charts-funnel.d.ts', TYPES, 'global not merged', 'interface ChartsGlobal extends FunnelApi {}', ''],
	['charts.d.ts', TYPES, 'core types lose palette', "palette(brand?: string, theme?: 'light' | 'dark'): Palette;", ''],
	['charts.d.ts', TYPES, 'palette theme is open', "palette(brand?: string, theme?: 'light' | 'dark'): Palette;", 'palette(brand?: string, theme?: string): Palette;'],
	['charts.d.ts', TYPES, 'core types the funnel', 'init(target: Element, svg: string): void;', 'init(target: Element, svg: string): void; funnel(...a: unknown[]): string;'],
].map(([file, gate, label, from, to]) => ({ file, gate, label, from, to }));

const BACKUP = 'temp/mutate';
const originals = new Map();
let dirty = null;

function restore() {
	if (!dirty) return;
	writeFileSync(dirty, originals.get(dirty));
	rmSync(`${BACKUP}/${dirty}`, { force: true });
	dirty = null;
}
process.on('exit', restore);
for (const sig of ['SIGINT', 'SIGTERM', 'SIGHUP']) process.on(sig, () => { restore(); process.exit(130); });

// a previous run that was killed hard left its backup: put the original back first
if (existsSync(BACKUP)) {
	for (const f of readdirSync(BACKUP)) {
		writeFileSync(f, readFileSync(`${BACKUP}/${f}`));
		console.log(`restored ${f} from a run that did not finish`);
	}
	rmSync(BACKUP, { recursive: true, force: true });
}
mkdirSync(BACKUP, { recursive: true });

// exit status 0 = green, 1 = red; anything else (killed, crashed: status null) is not evidence
function run([cmd, args]) {
	const r = spawnSync(cmd, args, { encoding: 'utf8' });
	return r.status === 0 ? 'green' : r.status === 1 ? 'red' : `broken (${r.status ?? r.signal})`;
}

for (const gate of [TEST, TYPES, BUNDLE, CAPPED]) {
	if (run(gate) !== 'green') {
		console.error(`the gate is not green before any mutation: ${gate[1].join(' ')}`);
		process.exit(1);
	}
}

let bad = 0;
for (const m of MUTATIONS) {
	if (!originals.has(m.file)) originals.set(m.file, readFileSync(m.file));
	const src = originals.get(m.file).toString('utf8');
	if (src.split(m.from).length !== 2) {
		console.log(`DRIFT    ${m.file}: ${m.label} — the anchor does not match exactly once`);
		bad++;
		continue;
	}
	writeFileSync(`${BACKUP}/${m.file}`, originals.get(m.file));
	dirty = m.file;
	writeFileSync(m.file, src.replace(m.from, m.to));
	const verdict = run(m.gate);
	restore();
	console.log(`${verdict === 'red' ? 'caught  ' : verdict === 'green' ? 'SURVIVED' : 'BROKEN  '} ${m.file}: ${m.label}${verdict.startsWith('broken') ? ` — gate ${verdict}` : ''}`);
	if (verdict !== 'red') bad++;
}
rmSync(BACKUP, { recursive: true, force: true });
console.log(bad ? `${bad} of ${MUTATIONS.length} mutations not caught` : `all ${MUTATIONS.length} mutations caught`);
process.exitCode = bad ? 1 : 0;
